export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const SENDOTP_REQUEST = "SENDOTP_REQUEST";
export const SENDOTP_SUCCESS = "SENDOTP_SUCCESS";
export const SENDOTP_FAILURE = "SENDOTP_FAILURE";

export const VERIFYOTP_REQUEST = "VERIFYOTP_REQUEST";
export const VERIFYOTP_SUCCESS = "VERIFYOTP_SUCCESS";
export const VERIFYOTP_FAILURE = "VERIFYOTP_FAILURE";

export const NEWPASSWORD_REQUEST = "NEWPASSWORD_REQUEST";
export const NEWPASSWORD_SUCCESS = "NEWPASSWORD_SUCCESS";
export const NEWPASSWORD_FAILURE = "NEWPASSWORD_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";


export const FETCH_ALLUSER_REQUEST = "FETCH_ALLUSER_REQUEST";
export const FETCH_ALLUSER_SUCCESS = "FETCH_ALLUSER_SUCCESS";
export const FETCH_ALLUSER_FAILURE = "FETCH_ALLUSER_FAILURE";

export const SENDMESSAGE_REQUEST = "SENDMESSAGE_REQUEST";
export const SENDMESSAGE_SUCCESS = "SENDMESSAGE_SUCCESS";
export const SENDMESSAGE_FAILURE = "SENDMESSAGE_FAILURE";

export const FETCH_MESSAGE_REQUEST = "FETCH_MESSAGE_REQUEST";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_FAILURE = "FETCH_MESSAGE_FAILURE";

export const SEEN_MESSAGE_REQUEST = "SEEN_MESSAGE_REQUEST";
export const SEEN_MESSAGE_SUCCESS = "SEEN_MESSAGE_SUCCESS";
export const SEEN_MESSAGE_FAILURE = "SEEN_MESSAGE_FAILURE";

export const UNSEEN_MESSAGE_REQUEST = "UNSEEN_MESSAGE_REQUEST";
export const UNSEEN_MESSAGE_SUCCESS = "UNSEEN_MESSAGE_SUCCESS";
export const UNSEEN_MESSAGE_FAILURE = "UNSEEN_MESSAGE_FAILURE";

export const UPDATEUSER_REQUEST = "UPDATEUSER_REQUEST";
export const UPDATEUSER_SUCCESS = "UPDATEUSER_SUCCESS";
export const UPDATEUSER_FAILURE = "UPDATEUSER_FAILURE";

